# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'problem3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);\n"
"background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.c4 = QtWidgets.QPushButton(self.centralwidget)
        self.c4.setGeometry(QtCore.QRect(80, 100, 41, 231))
        self.c4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.c4.setObjectName("c4")
        self.d4 = QtWidgets.QPushButton(self.centralwidget)
        self.d4.setGeometry(QtCore.QRect(120, 100, 41, 231))
        self.d4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d4.setObjectName("d4")
        self.e4 = QtWidgets.QPushButton(self.centralwidget)
        self.e4.setGeometry(QtCore.QRect(160, 100, 41, 231))
        self.e4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.e4.setObjectName("e4")
        self.f4 = QtWidgets.QPushButton(self.centralwidget)
        self.f4.setGeometry(QtCore.QRect(200, 100, 41, 231))
        self.f4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.f4.setObjectName("f4")
        self.g4 = QtWidgets.QPushButton(self.centralwidget)
        self.g4.setGeometry(QtCore.QRect(240, 100, 41, 231))
        self.g4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.g4.setObjectName("g4")
        self.a4 = QtWidgets.QPushButton(self.centralwidget)
        self.a4.setGeometry(QtCore.QRect(280, 100, 41, 231))
        self.a4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.a4.setObjectName("a4")
        self.b4 = QtWidgets.QPushButton(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(320, 100, 41, 231))
        self.b4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.b4.setObjectName("b4")
        self.c5 = QtWidgets.QPushButton(self.centralwidget)
        self.c5.setGeometry(QtCore.QRect(360, 100, 41, 231))
        self.c5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.c5.setObjectName("c5")
        self.d5 = QtWidgets.QPushButton(self.centralwidget)
        self.d5.setGeometry(QtCore.QRect(400, 100, 41, 231))
        self.d5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d5.setObjectName("d5")
        self.e5 = QtWidgets.QPushButton(self.centralwidget)
        self.e5.setGeometry(QtCore.QRect(440, 100, 41, 231))
        self.e5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.e5.setObjectName("e5")
        self.f5 = QtWidgets.QPushButton(self.centralwidget)
        self.f5.setGeometry(QtCore.QRect(480, 100, 41, 231))
        self.f5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.f5.setObjectName("f5")
        self.g5 = QtWidgets.QPushButton(self.centralwidget)
        self.g5.setGeometry(QtCore.QRect(520, 100, 41, 231))
        self.g5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.g5.setObjectName("g5")
        self.a5 = QtWidgets.QPushButton(self.centralwidget)
        self.a5.setGeometry(QtCore.QRect(560, 100, 41, 231))
        self.a5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.a5.setObjectName("a5")
        self.b5 = QtWidgets.QPushButton(self.centralwidget)
        self.b5.setGeometry(QtCore.QRect(600, 100, 41, 231))
        self.b5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.b5.setObjectName("b5")
        self.c40 = QtWidgets.QPushButton(self.centralwidget)
        self.c40.setGeometry(QtCore.QRect(100, 100, 31, 111))
        self.c40.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.c40.setObjectName("c40")
        self.d40 = QtWidgets.QPushButton(self.centralwidget)
        self.d40.setGeometry(QtCore.QRect(150, 100, 31, 111))
        self.d40.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.d40.setObjectName("d40")
        self.f40 = QtWidgets.QPushButton(self.centralwidget)
        self.f40.setGeometry(QtCore.QRect(220, 100, 31, 111))
        self.f40.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.f40.setObjectName("f40")
        self.g40 = QtWidgets.QPushButton(self.centralwidget)
        self.g40.setGeometry(QtCore.QRect(260, 100, 31, 111))
        self.g40.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.g40.setObjectName("g40")
        self.a40 = QtWidgets.QPushButton(self.centralwidget)
        self.a40.setGeometry(QtCore.QRect(300, 100, 31, 111))
        self.a40.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.a40.setObjectName("a40")
        self.c50 = QtWidgets.QPushButton(self.centralwidget)
        self.c50.setGeometry(QtCore.QRect(380, 100, 31, 111))
        self.c50.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.c50.setObjectName("c50")
        self.d50 = QtWidgets.QPushButton(self.centralwidget)
        self.d50.setGeometry(QtCore.QRect(420, 100, 31, 111))
        self.d50.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.d50.setObjectName("d50")
        self.f50 = QtWidgets.QPushButton(self.centralwidget)
        self.f50.setGeometry(QtCore.QRect(500, 100, 31, 111))
        self.f50.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.f50.setObjectName("f50")
        self.g50 = QtWidgets.QPushButton(self.centralwidget)
        self.g50.setGeometry(QtCore.QRect(540, 100, 31, 111))
        self.g50.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.g50.setObjectName("g50")
        self.a50 = QtWidgets.QPushButton(self.centralwidget)
        self.a50.setGeometry(QtCore.QRect(590, 100, 31, 111))
        self.a50.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.a50.setObjectName("a50")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(370, 40, 111, 22))
        self.comboBox.setStyleSheet("background-color: rgb(174, 196, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 261, 51))
        self.label.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(244, 224, 255);\n"
"color: rgb(174, 196, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 360, 351, 51))
        self.label_2.setStyleSheet("color: rgb(174, 196, 255);\n"
"color: rgb(89, 142, 191);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(192, 225, 99);\n"
"color: rgb(154, 147, 153);\n"
"color: rgb(174, 196, 255);\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.c4.raise_()
        self.d4.raise_()
        self.e4.raise_()
        self.f4.raise_()
        self.g4.raise_()
        self.a4.raise_()
        self.b4.raise_()
        self.c5.raise_()
        self.d5.raise_()
        self.e5.raise_()
        self.f5.raise_()
        self.g5.raise_()
        self.a5.raise_()
        self.b5.raise_()
        self.a40.raise_()
        self.a50.raise_()
        self.c40.raise_()
        self.c50.raise_()
        self.d40.raise_()
        self.d50.raise_()
        self.f40.raise_()
        self.f50.raise_()
        self.g40.raise_()
        self.g50.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.comboBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.c4.setText(_translate("MainWindow", "C4"))
        self.d4.setText(_translate("MainWindow", "D4"))
        self.e4.setText(_translate("MainWindow", "E4"))
        self.f4.setText(_translate("MainWindow", "F4"))
        self.g4.setText(_translate("MainWindow", "G4"))
        self.a4.setText(_translate("MainWindow", "A4"))
        self.b4.setText(_translate("MainWindow", "B4"))
        self.c5.setText(_translate("MainWindow", "C5"))
        self.d5.setText(_translate("MainWindow", "D5"))
        self.e5.setText(_translate("MainWindow", "E5"))
        self.f5.setText(_translate("MainWindow", "F5"))
        self.g5.setText(_translate("MainWindow", "G5"))
        self.a5.setText(_translate("MainWindow", "A5"))
        self.b5.setText(_translate("MainWindow", "B5"))
        self.c40.setText(_translate("MainWindow", "C4#"))
        self.d40.setText(_translate("MainWindow", "D4#"))
        self.f40.setText(_translate("MainWindow", "F4#"))
        self.g40.setText(_translate("MainWindow", "G4#"))
        self.a40.setText(_translate("MainWindow", "A4#"))
        self.c50.setText(_translate("MainWindow", "C5#"))
        self.d50.setText(_translate("MainWindow", "D5#"))
        self.f50.setText(_translate("MainWindow", "F5#"))
        self.g50.setText(_translate("MainWindow", "G5#"))
        self.a50.setText(_translate("MainWindow", "A5#"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Regular Piano"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Digital Piano"))
        self.label.setText(_translate("MainWindow", "Piano "))
        self.label_2.setText(_translate("MainWindow", "Please choose piano type"))

